### PR TITLE
Move PetriNets, PowerSystems and SystemDynamics to core libraries

### PR DESCRIPTION
**Pull request by adeas31**

### CODE REVIEW

**Review by sjoelund — COMMENTED** [review]
Are we really going to ship 2 copies of PowerSystems? Latest release should be fine, no?

**Review by sjoelund — CHANGES_REQUESTED** [review]
Makefile.libs is automatically generated from repos.json. Probably need to change the source or the changes disappear

**Comment by casella** [comment]
> 
> 
> Are we really going to ship 2 copies of PowerSystems? Latest release should be fine, no?

I guess 1.0.0 should be fine. 0.6.0 had some issues that were fixed, it probably doesn't work well in OpenModelica anyway.

**Comment by casella** [comment]
@rfranke, what do you think?

**Comment by adeas31** [comment]
> > Are we really going to ship 2 copies of PowerSystems? Latest release should be fine, no?
> 
> I guess 1.0.0 should be fine. 0.6.0 had some issues that were fixed, it probably doesn't work well in OpenModelica anyway.

1.0.0 tag or the latest (whatever in the master).

**Comment by adeas31** [comment]
> Makefile.libs is automatically generated from repos.json. Probably need to change the source or the changes disappear

I thought the same but then Makefile.libs is in the repo.

**Comment by sjoelund** [comment]
Yes, it's in the repo because we don't want to run the script to fetch all the information from GitHub on every build of OM. This way every system gets the same versions of the libraries as well.

**Comment by rfranke** [comment]
As discussed today, please use the master branch of PowerSystems.

**Comment by adeas31** [comment]
@adrpo and @sjoelund time to merge this.

**Comment by sjoelund** [comment]
There are conflicts :)

**Comment by adeas31** [comment]
It shows me "This branch has no conflicts with the base branch. Merging can be performed automatically."

**Comment by adeas31** [comment]
Anyway I merged in origin/master. We can now squash and merge.

**Comment by sjoelund** [comment]
Still no :)

**Review by sjoelund — APPROVED** [review]

**Comment by sjoelund** [comment]
Now I could...

**Pull request merged**
